require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CommingSoonsController do

  # This should return the minimal set of attributes required to create a valid
  # CommingSoon. As you add validations to CommingSoon, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CommingSoonsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all comming_soons as @comming_soons" do
      comming_soon = CommingSoon.create! valid_attributes
      get :index, {}, valid_session
      assigns(:comming_soons).should eq([comming_soon])
    end
  end

  describe "GET show" do
    it "assigns the requested comming_soon as @comming_soon" do
      comming_soon = CommingSoon.create! valid_attributes
      get :show, {:id => comming_soon.to_param}, valid_session
      assigns(:comming_soon).should eq(comming_soon)
    end
  end

  describe "GET new" do
    it "assigns a new comming_soon as @comming_soon" do
      get :new, {}, valid_session
      assigns(:comming_soon).should be_a_new(CommingSoon)
    end
  end

  describe "GET edit" do
    it "assigns the requested comming_soon as @comming_soon" do
      comming_soon = CommingSoon.create! valid_attributes
      get :edit, {:id => comming_soon.to_param}, valid_session
      assigns(:comming_soon).should eq(comming_soon)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CommingSoon" do
        expect {
          post :create, {:comming_soon => valid_attributes}, valid_session
        }.to change(CommingSoon, :count).by(1)
      end

      it "assigns a newly created comming_soon as @comming_soon" do
        post :create, {:comming_soon => valid_attributes}, valid_session
        assigns(:comming_soon).should be_a(CommingSoon)
        assigns(:comming_soon).should be_persisted
      end

      it "redirects to the created comming_soon" do
        post :create, {:comming_soon => valid_attributes}, valid_session
        response.should redirect_to(CommingSoon.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved comming_soon as @comming_soon" do
        # Trigger the behavior that occurs when invalid params are submitted
        CommingSoon.any_instance.stub(:save).and_return(false)
        post :create, {:comming_soon => {}}, valid_session
        assigns(:comming_soon).should be_a_new(CommingSoon)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CommingSoon.any_instance.stub(:save).and_return(false)
        post :create, {:comming_soon => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested comming_soon" do
        comming_soon = CommingSoon.create! valid_attributes
        # Assuming there are no other comming_soons in the database, this
        # specifies that the CommingSoon created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CommingSoon.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => comming_soon.to_param, :comming_soon => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested comming_soon as @comming_soon" do
        comming_soon = CommingSoon.create! valid_attributes
        put :update, {:id => comming_soon.to_param, :comming_soon => valid_attributes}, valid_session
        assigns(:comming_soon).should eq(comming_soon)
      end

      it "redirects to the comming_soon" do
        comming_soon = CommingSoon.create! valid_attributes
        put :update, {:id => comming_soon.to_param, :comming_soon => valid_attributes}, valid_session
        response.should redirect_to(comming_soon)
      end
    end

    describe "with invalid params" do
      it "assigns the comming_soon as @comming_soon" do
        comming_soon = CommingSoon.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CommingSoon.any_instance.stub(:save).and_return(false)
        put :update, {:id => comming_soon.to_param, :comming_soon => {}}, valid_session
        assigns(:comming_soon).should eq(comming_soon)
      end

      it "re-renders the 'edit' template" do
        comming_soon = CommingSoon.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CommingSoon.any_instance.stub(:save).and_return(false)
        put :update, {:id => comming_soon.to_param, :comming_soon => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested comming_soon" do
      comming_soon = CommingSoon.create! valid_attributes
      expect {
        delete :destroy, {:id => comming_soon.to_param}, valid_session
      }.to change(CommingSoon, :count).by(-1)
    end

    it "redirects to the comming_soons list" do
      comming_soon = CommingSoon.create! valid_attributes
      delete :destroy, {:id => comming_soon.to_param}, valid_session
      response.should redirect_to(comming_soons_url)
    end
  end

end
